import type { Metadata } from "next";
import { Montserrat, Teko } from "next/font/google";
import "./globals.css";

const teko = Teko({ subsets: ["latin"], variable: "--font-teko" });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${teko.variable} ${montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
